name: light_listen
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  oktoast: ^2.3.0
  provider: 4.0.2
  cookie_jar: 1.0.1
  url_launcher: 5.4.1
  dio: 2.2.2
  shared_preferences: 0.5.6
  connectivity: ^0.4.6+2
  flutter_svg: ^0.15.0
  path_provider: 1.5.1
  common_utils: ^1.1.3
  extended_image: ^0.6.9
  flutter_inappwebview:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview.git
      ref: "9c7ac0da8f01ceb40430da58397bdb31968ca5b1"
  hive: 1.3.0
  hive_flutter: ^0.3.0
  flutter_screenutil: ^0.7.0
  flutter_platform_widgets: ^0.31.0
  carousel_slider: ^1.4.1
  audioplayers: ^0.13.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  ff_annotation_route: any


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/settings/
    - images/controller/
    - images/player/
    - images/daily/
    - images/action/
    - images/playlist/

  fonts:
    - family: iconfont
      fonts:
        - asset: fonts/iconfont.ttf
    - family: chocolate
      fonts:
        - asset: fonts/chocolate.ttf
    - family: fzsjt
      fonts:
        - asset: fonts/fzsjt.ttf