// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************

import 'package:flutter/widgets.dart';

import 'page/album/album_detail_page.dart';
import 'page/home/home_page.dart';
import 'page/player/player_page.dart';
import 'page/setting/font_scale_page.dart';
import 'page/setting/change_theme_page.dart';
import 'page/setting/settings_page.dart';
import 'page/other/in_app_webview.dart';
import 'page/other/login_page.dart';
import 'page/other/splash_page.dart';
import 'page/other/register_page.dart';
import 'page/musiclist/music_list__detail_page.dart';
import 'page/action/action_daily_music_page.dart';
import 'page/action/action_video_page.dart';
import 'page/action/action_artist_page.dart';
import 'page/action/action_music_list_page.dart';
import 'page/action/action_rank_page.dart';
import 'package:ff_annotation_route/ff_annotation_route.dart';

RouteResult getRouteResult({String name, Map<String, dynamic> arguments}) {
  switch (name) {
    case "lightlisten://album_detail_page":
      return RouteResult(
        widget: AlbumDetailPage(
          album: arguments['album'],
        ),
        routeName: "album_detail_page",
        pageRouteType: PageRouteType.material,
      );
    case "lightlisten://home":
      return RouteResult(
        widget: HomePage(),
        routeName: "home",
        pageRouteType: PageRouteType.material,
      );
    case "lightlisten://player":
      return RouteResult(
        widget: PlayerPage(),
        routeName: "player",
        pageRouteType: PageRouteType.material,
      );
    case "lightlisten://font-scale":
      return RouteResult(
        widget: FontScalePage(),
        routeName: "font-scale",
        pageRouteType: PageRouteType.material,
      );
    case "lightlisten://theme":
      return RouteResult(
        widget: ChangeThemePage(),
        routeName: "theme",
        pageRouteType: PageRouteType.material,
      );
    case "lightlisten://settings":
      return RouteResult(
        widget: SettingsPage(),
        routeName: "settings",
        pageRouteType: PageRouteType.material,
      );
    case "lightlisten://inappbrowser":
      return RouteResult(
        widget: InAppBrowserPage(
          url: arguments['url'],
          title: arguments['title'],
          withCookie: arguments['withCookie'],
          withAppBar: arguments['withAppBar'],
          withAction: arguments['withAction'],
          withScaffold: arguments['withScaffold'],
          keepAlive: arguments['keepAlive'],
        ),
        routeName: "inappbrowser",
      );
    case "lightlisten://login":
      return RouteResult(
        widget: LoginPage(),
        routeName: "login",
        pageRouteType: PageRouteType.material,
      );
    case "lightlisten://splash":
      return RouteResult(
        widget: SplashPage(),
        routeName: "splash",
        pageRouteType: PageRouteType.material,
      );
    case "lightlisten://register":
      return RouteResult(
        widget: RegisterPage(),
        routeName: "register",
        pageRouteType: PageRouteType.material,
      );
    case "lightlisten://music_list_detail":
      return RouteResult(
        widget: MusicListDetailPage(
          id: arguments['id'],
          name: arguments['name'],
          picUrl: arguments['picUrl'],
          nikeName: arguments['nikeName'],
          avatarUrl: arguments['avatarUrl'],
        ),
        routeName: "music_list_detail",
        pageRouteType: PageRouteType.material,
      );
    case "lightlisten://action_daily_music":
      return RouteResult(
        widget: DailyMusicPage(),
        routeName: "action_daily_music",
        pageRouteType: PageRouteType.material,
      );
    case "lightlisten://action_video":
      return RouteResult(
        widget: ActionVideoPage(),
        routeName: "action_video",
        pageRouteType: PageRouteType.material,
      );
    case "lightlisten://action_artist":
      return RouteResult(
        widget: ActionArtistPage(),
        routeName: "action_artist",
        pageRouteType: PageRouteType.material,
      );
    case "lightlisten://action_music_list":
      return RouteResult(
        widget: ActionSongListPage(),
        routeName: "action_music_list",
        pageRouteType: PageRouteType.material,
      );
    case "lightlisten://action_rank":
      return RouteResult(
        widget: ActionRankPage(),
        routeName: "action_rank",
        pageRouteType: PageRouteType.material,
      );
    default:
      return RouteResult();
  }
}

class RouteResult {
  /// The Widget return base on route
  final Widget widget;

  /// Whether show this route with status bar.
  final bool showStatusBar;

  /// The route name to track page
  final String routeName;

  /// The type of page route
  final PageRouteType pageRouteType;

  /// The description of route
  final String description;

  const RouteResult(
      {this.widget, this.showStatusBar = true, this.routeName = '', this.pageRouteType, this.description = ''});
}

//enum PageRouteType { material, cupertino, transparent }

List<String> routeNames = [
  "lightlisten://album_detail_page",
  "lightlisten://home",
  "lightlisten://player",
  "lightlisten://font-scale",
  "lightlisten://theme",
  "lightlisten://settings",
  "lightlisten://inappbrowser",
  "lightlisten://login",
  "lightlisten://splash",
  "lightlisten://register",
  "lightlisten://music_list_detail",
  "lightlisten://action_daily_music",
  "lightlisten://action_video",
  "lightlisten://action_artist",
  "lightlisten://action_music_list",
  "lightlisten://action_rank"
];

class Routes {
  /// album_detail_page
  ///
  /// [name] : lightlisten://album_detail_page
  /// [routeName] : album_detail_page
  /// [arguments] : [album]
  /// [pageRouteType] : PageRouteType.material
  static const String LIGHTLISTEN_ALBUM_DETAIL_PAGE = "lightlisten://album_detail_page";

  /// home
  ///
  /// [name] : lightlisten://home
  /// [routeName] : home
  /// [pageRouteType] : PageRouteType.material
  static const String LIGHTLISTEN_HOME = "lightlisten://home";

  /// player
  ///
  /// [name] : lightlisten://player
  /// [routeName] : player
  /// [pageRouteType] : PageRouteType.material
  static const String LIGHTLISTEN_PLAYER = "lightlisten://player";

  /// font-scale
  ///
  /// [name] : lightlisten://font-scale
  /// [routeName] : font-scale
  /// [pageRouteType] : PageRouteType.material
  static const String LIGHTLISTEN_FONT_SCALE = "lightlisten://font-scale";

  /// theme
  ///
  /// [name] : lightlisten://theme
  /// [routeName] : theme
  /// [pageRouteType] : PageRouteType.material
  static const String LIGHTLISTEN_THEME = "lightlisten://theme";

  /// settings
  ///
  /// [name] : lightlisten://settings
  /// [routeName] : settings
  /// [pageRouteType] : PageRouteType.material
  static const String LIGHTLISTEN_SETTINGS = "lightlisten://settings";

  /// inappbrowser
  ///
  /// [name] : lightlisten://inappbrowser
  /// [routeName] : inappbrowser
  /// [arguments] : [url, title, withCookie, withAppBar, withAction, withScaffold, keepAlive]
  static const String LIGHTLISTEN_INAPPBROWSER = "lightlisten://inappbrowser";

  /// login
  ///
  /// [name] : lightlisten://login
  /// [routeName] : login
  /// [pageRouteType] : PageRouteType.material
  static const String LIGHTLISTEN_LOGIN = "lightlisten://login";

  /// splash
  ///
  /// [name] : lightlisten://splash
  /// [routeName] : splash
  /// [pageRouteType] : PageRouteType.material
  static const String LIGHTLISTEN_SPLASH = "lightlisten://splash";

  /// register
  ///
  /// [name] : lightlisten://register
  /// [routeName] : register
  /// [pageRouteType] : PageRouteType.material
  static const String LIGHTLISTEN_REGISTER = "lightlisten://register";

  /// music_list_detail
  ///
  /// [name] : lightlisten://music_list_detail
  /// [routeName] : music_list_detail
  /// [arguments] : [music_list]
  /// [pageRouteType] : PageRouteType.material
  static const String LIGHTLISTEN_MUSIC_LIST_DETAIL = "lightlisten://music_list_detail";

  /// action_daily_music
  ///
  /// [name] : lightlisten://action_daily_music
  /// [routeName] : action_daily_music
  /// [pageRouteType] : PageRouteType.material
  static const String LIGHTLISTEN_ACTION_DAILY_MUSIC = "lightlisten://action_daily_music";

  /// action_video
  ///
  /// [name] : lightlisten://action_video
  /// [routeName] : action_video
  /// [pageRouteType] : PageRouteType.material
  static const String LIGHTLISTEN_ACTION_VIDEO = "lightlisten://action_video";

  /// action_artist
  ///
  /// [name] : lightlisten://action_artist
  /// [routeName] : action_artist
  /// [pageRouteType] : PageRouteType.material
  static const String LIGHTLISTEN_ACTION_ARTIST = "lightlisten://action_artist";

  /// action_music_list
  ///
  /// [name] : lightlisten://action_music_list
  /// [routeName] : action_music_list
  /// [pageRouteType] : PageRouteType.material
  static const String LIGHTLISTEN_ACTION_MUSIC_LIST = "lightlisten://action_music_list";

  /// action_rank
  ///
  /// [name] : lightlisten://action_rank
  /// [routeName] : action_rank
  /// [pageRouteType] : PageRouteType.material
  static const String LIGHTLISTEN_ACTION_RANK = "lightlisten://action_rank";
}
